In [1]:
import pandas as pd

In [2]:
EM_data = pd.read_csv("K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\Conversion_Paths\\EM_responders_jul_dec_22.csv")

In [3]:
DM_data = pd.read_csv("K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\Conversion_Paths\\DM_responders_jul_dec_22.csv")

In [4]:
SM_data = pd.read_csv("K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\Conversion_Paths\\SM_responders_jul_dec_22.csv")

In [5]:
dm_2019 = pd.read_csv('K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\DM\\DM_responders_2019.csv')

In [6]:
print(EM_data.shape)
print(DM_data.shape)
print(SM_data.shape)

(127091, 7)
(28047, 7)
(2309, 7)

In [40]:
dm_2019.head()

,CURR_AG_IND_ID,COMMUNICATION_ID,drop_date,first_purch_dt,no_of_touches,days_to_resp,wt_resp,drop_date2
0,1000000000349,EPSI_158394137-1076713073,24MAY2019,13JUN2019,2,20,0.138011,2019-05-24
1,1000000000349,EPSI_156486863-1042698694,26APR2019,13JUN2019,2,48,0.008626,2019-04-26
2,1000000001043,EPSI_168749298-1167048929,22NOV2019,10DEC2019,1,18,0.168238,2019-11-22
3,1000000001072,EPSI_161957696-1106504543,16JUL2019,29JUL2019,1,13,0.276022,2019-07-16
4,1000000001072,EPSI_170442607-1178637060,22DEC2019,11FEB2020,1,51,0.006409,2019-12-22

In [41]:
dm_2019['drop_date2'] = pd.to_datetime(
                          dm_2019['drop_date'],
                          format='%d%b%Y'
)

dm_2019_2 = dm_2019[dm_2019['drop_date2'] > '2019-07-01']

dm_2019_2['Channel'] = 'DM'
dm_2019_3 = dm_2019_2[dm_2019_2['days_to_resp']<=60]

C:\Users\rthomas\AppData\Local\Temp\38\ipykernel_45752\1278897819.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dm_2019_2['Channel'] = 'DM'

In [42]:
Digital_data = pd.read_excel('K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\Digital\\Time Series Data_V2.xlsx')

In [43]:
Digital_data2 = Digital_data[(Digital_data['Web_channel']!='Third Party')&(Digital_data['Web_channel']!=1024)]

In [10]:
Digital_data2.head()

,CURR_AG_IND_ID,COMM_ID,Event_Date,first_purch_dt,no_of_touches,days_to_resp,wt_resp,Web_channel
0,1000000000265,1.643322e+12,2022-01-27,2022-07-11,2,165,8.022190e-08,Organic
1,1000000000265,1.644017e+12,2022-02-04,2022-08-26,1,203,1.862645e-09,Organic
2,1000000000265,1.644270e+12,2022-02-07,2022-11-12,1,278,1.108686e-12,Organic
3,1000000000265,1.654634e+12,2022-06-07,2022-06-13,1,6,5.520448e-01,Organic
4,1000000000265,1.655927e+12,2022-06-22,2022-06-23,1,1,9.057237e-01,Organic

In [11]:
print(Digital_data2.shape)
Digital_data3 = Digital_data2[Digital_data2['Event_Date'] > '2022-07-01']
print(Digital_data3.shape)

(95890, 8)
(61703, 8)

In [15]:
Digital_data3.head()

,CURR_AG_IND_ID,COMM_ID,Event_Date,first_purch_dt,no_of_touches,days_to_resp,wt_resp,Web_channel
6,1000000000265,1.657217e+12,2022-07-07,2022-07-26,2,19,0.152377,Organic
7,1000000000265,1.657294e+12,2022-07-08,2022-07-15,1,7,0.500000,Organic
8,1000000000265,1.657308e+12,2022-07-08,2022-07-26,2,18,0.168238,Organic
9,1000000000759,4.335900e+05,2022-09-04,2022-09-15,2,11,0.336475,Display
10,1000000000759,4.336710e+05,2022-09-11,2022-09-15,2,4,0.672950,Display

In [12]:
ThirdParty_data = pd.read_excel('K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\Digital\\Third Party Data_New.xlsx')
ThirdParty_data.head()

,CURR_AG_IND_ID,LEAD_ID,Event_Date,first_purch_dt,no_of_touches,days_to_resp,wt_resp,Web_channel
0,1000000002960,341706772,2022-04-29,2022-04-30,2,1,9.057237e-01,Third Party
1,1000000002960,339395283,2022-04-18,2022-04-30,2,12,3.047534e-01,Third Party
2,1000000004687,376482148,2023-01-09,2023-02-03,1,25,8.411876e-02,Third Party
3,1000000004716,359653575,2022-07-14,2022-08-29,1,46,1.051485e-02,Third Party
4,1000000004863,339343011,2022-04-15,2023-01-21,2,281,8.237509e-13,Third Party

In [13]:
print(ThirdParty_data.shape)
ThirdParty_data2 = ThirdParty_data[ThirdParty_data['Event_Date'] > '2022-07-01']
print(ThirdParty_data2.shape)

(74242, 8)
(47049, 8)

In [14]:
Digital_data3 = Digital_data2.rename(columns = {'COMM_ID':'COMMUNICATION_ID', 'Web_channel':'Channel','Event_Date':'drop_date'
                              })
ThirdParty_data2 = ThirdParty_data.rename(columns = {'LEAD_ID':'COMMUNICATION_ID', 'Web_channel':'Channel','Event_Date':'drop_date'
                              })

In [15]:
EM_data['first_purch_dt2'] = pd.to_datetime(
                          EM_data['first_purch_dt'],
                          format='%d%b%Y'
)
EM_data['drop_date2'] = pd.to_datetime(
                          EM_data['drop_date'],
                          format='%d%b%Y'
)

In [16]:
DM_data['first_purch_dt2'] = pd.to_datetime(
                          DM_data['first_purch_dt'],
                          format='%d%b%Y'
)
DM_data['drop_date2'] = pd.to_datetime(
                          DM_data['drop_date'],
                          format='%d%b%Y'
)

In [17]:
SM_data['first_purch_dt2'] = pd.to_datetime(
                          SM_data['first_purch_dt'],
                          format='%d%b%Y'
)
SM_data['drop_date2'] = pd.to_datetime(
                          SM_data['drop_date'],
                          format='%d%b%Y'
)

In [18]:
Digital_data3['first_purch_dt2'] = pd.to_datetime(
                          Digital_data3['first_purch_dt'],
                          format='%Y-%m-%d'
)
Digital_data3['drop_date2'] = pd.to_datetime(
                          Digital_data3['drop_date'],
                          format='%Y-%m-%d'
)

In [19]:
ThirdParty_data2['first_purch_dt2'] = pd.to_datetime(
                          ThirdParty_data2['first_purch_dt'],
                          format='%Y-%m-%d'
)
ThirdParty_data2['drop_date2'] = pd.to_datetime(
                          ThirdParty_data2['drop_date'],
                          format='%Y-%m-%d'
)

In [20]:
EM_data['Channel'] = 'EM'
DM_data['Channel'] = 'DM'
SM_data['Channel'] = 'SM'

In [22]:
EM_data2 = EM_data[EM_data['days_to_resp']<=30]
SM_data2 = SM_data[SM_data['days_to_resp']<=30]
DM_data2 = DM_data[DM_data['days_to_resp']<=60]
Digital_data4 = Digital_data3[Digital_data3['days_to_resp']<=30]
ThirdParty_data3 = ThirdParty_data2[ThirdParty_data2['days_to_resp']<=30]

In [23]:
ThirdParty_data3.head()

,CURR_AG_IND_ID,COMMUNICATION_ID,drop_date,first_purch_dt,no_of_touches,days_to_resp,wt_resp,Channel,first_purch_dt2,drop_date2
0,1000000002960,341706772,2022-04-29,2022-04-30,2,1,0.905724,Third Party,2022-04-30,2022-04-29
1,1000000002960,339395283,2022-04-18,2022-04-30,2,12,0.304753,Third Party,2022-04-30,2022-04-18
2,1000000004687,376482148,2023-01-09,2023-02-03,1,25,0.084119,Third Party,2023-02-03,2023-01-09
7,1000000004983,376318417,2023-01-05,2023-01-06,2,1,0.905724,Third Party,2023-01-06,2023-01-05
8,1000000005355,361063074,2022-07-21,2022-07-27,1,6,0.552045,Third Party,2022-07-27,2022-07-21

In [68]:
comb = pd.concat([EM_data2,SM_data2, DM_data2, Digital_data4, ThirdParty_data3], axis=0)
print(comb.shape)

(293479, 10)

In [69]:
comb2 = comb.sort_values(['CURR_AG_IND_ID', 'first_purch_dt2','drop_date2'],
              ascending = [True, True, True])

In [70]:
comb3 = comb2[['CURR_AG_IND_ID','first_purch_dt2','days_to_resp','drop_date2','Channel']]
comb3.head()

   CURR_AG_IND_ID first_purch_dt2  days_to_resp drop_date2  Channel
1   1000000000207      2022-07-28             8 2022-07-20       EM
0   1000000000207      2022-07-28             1 2022-07-27       EM
3   1000000000265      2022-06-13             6 2022-06-07  Organic
4   1000000000265      2022-06-23             1 2022-06-22  Organic
5   1000000000265      2022-07-11            13 2022-06-28  Organic

In [71]:
count1 = comb3.groupby(['CURR_AG_IND_ID','first_purch_dt2'])['Channel'].nunique().reset_index().rename(columns={'Channel':'Unique_channels'})
count1.head()

   CURR_AG_IND_ID first_purch_dt2  Unique_channels
0   1000000000207      2022-07-28                1
1   1000000000265      2022-06-13                1
2   1000000000265      2022-06-23                1
3   1000000000265      2022-07-11                1
4   1000000000265      2022-07-15                1

In [72]:
comb4 = pd.merge(comb3, count1, how = 'left', on = ['CURR_AG_IND_ID','first_purch_dt2'])
comb4.head()

,CURR_AG_IND_ID,first_purch_dt2,days_to_resp,drop_date2,Channel,Unique_channels
0,1000000000207,2022-07-28,8,2022-07-20,EM,1
1,1000000000207,2022-07-28,1,2022-07-27,EM,1
2,1000000000265,2022-06-13,6,2022-06-07,Organic,1
3,1000000000265,2022-06-23,1,2022-06-22,Organic,1
4,1000000000265,2022-07-11,13,2022-06-28,Organic,1

In [73]:
comb4.groupby('Channel')['CURR_AG_IND_ID'].nunique()

Channel
DM             21824
Display        31283
EM             57016
Organic        15788
SEM            11836
SM               847
Social           928
Third Party    53053
Name: CURR_AG_IND_ID, dtype: int64

In [96]:
print(comb4.shape)
comb5 = comb4[comb4['Unique_channels'] > 1]
print(comb5.shape)
comb5.head()

(294366, 6)
(68303, 6)

,CURR_AG_IND_ID,first_purch_dt2,days_to_resp,drop_date2,Channel,Unique_channels
10,1000000000432,2022-11-25,49,2022-10-07,DM,2
11,1000000000432,2022-11-25,17,2022-11-08,EM,2
12,1000000000432,2022-11-25,10,2022-11-15,DM,2
13,1000000000432,2022-11-25,7,2022-11-18,EM,2
14,1000000000432,2022-11-25,2,2022-11-23,EM,2

In [32]:
agg1 = comb5.groupby(['CURR_AG_IND_ID','first_purch_dt2']).agg({'Channel': '-->'.join}).reset_index()
agg1

       CURR_AG_IND_ID first_purch_dt2                 Channel
0       1000000000432      2022-11-25  DM-->EM-->DM-->EM-->EM
1       1000000001072      2022-10-11                 EM-->DM
2       1000000001396      2022-07-27       EM-->EM-->Display
3       1000000003978      2022-04-01            SEM-->Social
4       1000000004687      2023-02-03   Third Party-->Display
...               ...             ...                     ...
20941   1000127304312      2023-02-13           Organic-->SEM
20942   1000127490959      2023-02-18           SEM-->Organic
20943   1000127508799      2023-02-18           Organic-->SEM
20944   1000127544835      2023-02-17           SEM-->Organic
20945   1000128120421      2023-02-21           SEM-->Organic

[20946 rows x 3 columns]

In [119]:
a1 = comb5[comb5['Channel']=='Third Party']
a1.shape

(6823, 6)

In [33]:
agg1 = comb5.groupby(['CURR_AG_IND_ID','first_purch_dt2']).agg({'Channel': '-->'.join}).reset_index()
agg1

       CURR_AG_IND_ID first_purch_dt2                 Channel
0       1000000000432      2022-11-25  DM-->EM-->DM-->EM-->EM
1       1000000001072      2022-10-11                 EM-->DM
2       1000000001396      2022-07-27       EM-->EM-->Display
3       1000000003978      2022-04-01            SEM-->Social
4       1000000004687      2023-02-03   Third Party-->Display
...               ...             ...                     ...
20941   1000127304312      2023-02-13           Organic-->SEM
20942   1000127490959      2023-02-18           SEM-->Organic
20943   1000127508799      2023-02-18           Organic-->SEM
20944   1000127544835      2023-02-17           SEM-->Organic
20945   1000128120421      2023-02-21           SEM-->Organic

[20946 rows x 3 columns]

In [121]:
pat1 = pd.DataFrame(agg1['Channel'].value_counts()).reset_index()
pat1.columns = ['Conv_path', 'Frequency']
print(pat1.shape)

(1835, 2)

In [87]:
pat1 = pd.DataFrame(agg1['Channel'].value_counts()).reset_index()
pat1.columns = ['Conv_path', 'Frequency']
print(pat1.shape)

(1301, 2)

In [122]:
pat1.head(30)

                          Conv_path  Frequency
0                           DM-->EM       1164
1                      EM-->Display        809
2             Third Party-->Display        788
3             Display-->Third Party        787
4                      DM-->EM-->EM        787
5                 EM-->EM-->Display        546
6                      DM-->Display        526
7                  EM-->Third Party        439
8                           EM-->DM        423
9                 DM-->EM-->EM-->EM        422
10                Organic-->Display        387
11           EM-->EM-->EM-->Display        325
12                     Display-->EM        307
13                    SEM-->Display        277
14                Display-->Organic        259
15                SEM-->Third Party        255
16            Organic-->Third Party        246
17                     DM-->DM-->EM        245
18                 DM-->Third Party        228
19                     DM-->EM-->DM        223
20            EM-->EM-->Third Party        220
21                     EM-->EM-->DM        214
22                     EM-->DM-->EM        213
23            Third Party-->Organic        211
24           DM-->EM-->EM-->EM-->EM        209
25                     EM-->Organic        187
26  Display-->Display-->Third Party        187
27                EM-->Display-->EM        185
28                 Third Party-->EM        174
29                    Display-->SEM        152

In [123]:
pat1.to_csv('K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\Conversion_Paths\\AllChannel_ConvPaths_Mar1.csv', index = False)

In [39]:
# For Single Channels

In [60]:
print(comb4.shape)
comb6 = comb4[comb4['Unique_channels'] == 1]
print(comb6.shape)
comb6.head()

(293479, 6)
(225870, 6)

,CURR_AG_IND_ID,first_purch_dt2,days_to_resp,drop_date2,Channel,Unique_channels
0,1000000000207,2022-07-28,8,2022-07-20,EM,1
1,1000000000207,2022-07-28,1,2022-07-27,EM,1
2,1000000000265,2022-06-13,6,2022-06-07,Organic,1
3,1000000000265,2022-06-23,1,2022-06-22,Organic,1
4,1000000000265,2022-07-11,13,2022-06-28,Organic,1

In [61]:
comb6.groupby('Channel')['CURR_AG_IND_ID'].nunique()

Channel
DM             13676
Display        21481
EM             44006
Organic        13067
SEM             9626
SM               205
Social           720
Third Party    47263
Name: CURR_AG_IND_ID, dtype: int64

In [98]:
comb6['Unique_veh_purch_id'] = comb6['CURR_AG_IND_ID'].astype(str).str.cat(comb6['first_purch_dt2'].astype(str))

C:\Users\rthomas\AppData\Local\Temp\21\ipykernel_24440\4144426693.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comb6['Unique_veh_purch_id'] = comb6['CURR_AG_IND_ID'].astype(str).str.cat(comb6['first_purch_dt2'].astype(str))

In [99]:
comb6.groupby('Channel')['Unique_veh_purch_id'].nunique()

Channel
DM             14355
Display        21608
EM             49620
Organic        20470
SEM            10997
SM               208
Social           719
Third Party    47307
Name: Unique_veh_purch_id, dtype: int64

In [67]:
agg2 = comb6.groupby(['CURR_AG_IND_ID','first_purch_dt2']).agg({'Channel': '-->'.join}).reset_index()
agg2

        CURR_AG_IND_ID first_purch_dt2  Channel
0        1000000000207      2022-07-28  EM-->EM
1        1000000000265      2022-06-13  Organic
2        1000000000265      2022-06-23  Organic
3        1000000000265      2022-07-11  Organic
4        1000000000265      2022-07-15  Organic
...                ...             ...      ...
158356   1000128364494      2023-02-10  Organic
158357   1000128364494      2023-02-14  Organic
158358   1000128364494      2023-02-19  Organic
158359   1000128379520      2022-12-15      SEM
158360   1000128393839      2022-10-31  Organic

[158361 rows x 3 columns]

In [68]:
pat2 = pd.DataFrame(agg2['Channel'].value_counts()).reset_index()
pat2.columns = ['Conv_path', 'Frequency']
print(pat2.shape)

(57, 2)

In [69]:
pat2.head(30)

                                            Conv_path  Frequency
0                                         Third Party      43225
1                                                  EM      27775
2                                             Organic      19804
3                                             Display      17389
4                                             EM-->EM      14081
5                                                 SEM      10780
6                                        EM-->EM-->EM       7308
7                                   EM-->EM-->EM-->EM       3813
8                                   Display-->Display       3698
9                           Third Party-->Third Party       3681
10                             EM-->EM-->EM-->EM-->EM       1579
11                        Display-->Display-->Display       1005
12                                  Organic-->Organic        772
13                                             Social        702
14                        EM-->EM-->EM-->EM-->EM-->EM        612
15            Third Party-->Third Party-->Third Party        582
16              Display-->Display-->Display-->Display        361
17                                          SEM-->SEM        298
18                                                 SM        187
19                   EM-->EM-->EM-->EM-->EM-->EM-->EM        171
20  Third Party-->Third Party-->Third Party-->Thir...        129
21    Display-->Display-->Display-->Display-->Display        120
22              EM-->EM-->EM-->EM-->EM-->EM-->EM-->EM         73
23                                            SM-->SM         32
24  Third Party-->Third Party-->Third Party-->Thir...         28
25                                    Social-->Social         20
26  Display-->Display-->Display-->Display-->Displa...         20
27         EM-->EM-->EM-->EM-->EM-->EM-->EM-->EM-->EM         20
28                        Organic-->Organic-->Organic         14
29  Third Party-->Third Party-->Third Party-->Thir...         11

In [129]:
pat2.to_csv('K:\\autonation\\ANALYTICS\\Other Analysis Related\\DecayAttribution\\Data\\Conversion_Paths\\SingleChannel_ConvPaths_Mar1.csv', index = False)

In [45]:
pat2.head(20)

                                  Conv_path  Frequency
0                               Third Party      44116
1                                        EM      26033
2                                   EM-->EM      12740
3                                        DM      11985
4                                   Display      11146
5                                   Organic       6861
6                              EM-->EM-->EM       6426
7                 Third Party-->Third Party       3751
8                                       SEM       3520
9                         EM-->EM-->EM-->EM       3343
10                                  DM-->DM       2108
11                        Display-->Display       1845
12                   EM-->EM-->EM-->EM-->EM       1357
13  Third Party-->Third Party-->Third Party        603
14              Display-->Display-->Display        564
15              EM-->EM-->EM-->EM-->EM-->EM        537
16                                   Social        231
17    Display-->Display-->Display-->Display        212
18                        Organic-->Organic        185
19                                       SM        180

In [34]:
agg3 = comb4.groupby(['CURR_AG_IND_ID','first_purch_dt2']).agg({'Channel': '-->'.join}).reset_index()
agg3

        CURR_AG_IND_ID first_purch_dt2  Channel
0        1000000000207      2022-07-28  EM-->EM
1        1000000000265      2022-06-13  Organic
2        1000000000265      2022-06-23  Organic
3        1000000000265      2022-07-11  Organic
4        1000000000265      2022-07-15  Organic
...                ...             ...      ...
186047   1000128364494      2023-02-10  Organic
186048   1000128364494      2023-02-14  Organic
186049   1000128364494      2023-02-19  Organic
186050   1000128379520      2022-12-15      SEM
186051   1000128393839      2022-10-31  Organic

[186052 rows x 3 columns]

In [52]:
pat4 = agg3.groupby('Channel')['CURR_AG_IND_ID'].nunique().reset_index().sort_values(['CURR_AG_IND_ID'],ascending=False)
pat4.head(50)

                                      Channel  CURR_AG_IND_ID
1752                              Third Party           42889
779                                        EM           22808
547                                   Display           16522
1474                                  Organic           12733
937                                   EM-->EM           11991
0                                          DM           11597
1558                                      SEM            9335
1027                             EM-->EM-->EM            6181
1844                Third Party-->Third Party            3634
563                         Display-->Display            3546
1072                        EM-->EM-->EM-->EM            3228
1                                     DM-->DM            2054
1102                   EM-->EM-->EM-->EM-->EM            1308
195                                   DM-->EM            1161
571               Display-->Display-->Display             961
841                              EM-->Display             808
1758                    Third Party-->Display             788
756                     Display-->Third Party             787
280                              DM-->EM-->EM             784
1516                        Organic-->Organic             767
1724                                   Social             696
1875  Third Party-->Third Party-->Third Party             577
969                         EM-->EM-->Display             546
129                              DM-->Display             525
1125              EM-->EM-->EM-->EM-->EM-->EM             516
1440                         EM-->Third Party             438
780                                   EM-->DM             422
342                         DM-->EM-->EM-->EM             422
1478                        Organic-->Display             387
576     Display-->Display-->Display-->Display             341
1039                   EM-->EM-->EM-->Display             325
664                              Display-->EM             307
1610                                SEM-->SEM             298
1563                            SEM-->Display             277
723                         Display-->Organic             259
1632                        SEM-->Third Party             255
1548                    Organic-->Third Party             246
37                               DM-->DM-->EM             245
520                          DM-->Third Party             228
196                              DM-->EM-->DM             223
1315                    EM-->EM-->Third Party             220
938                              EM-->EM-->DM             214
1809                    Third Party-->Organic             211
795                              EM-->DM-->EM             211
368                    DM-->EM-->EM-->EM-->EM             209
1343                             EM-->Organic             187
657           Display-->Display-->Third Party             187
879                         EM-->Display-->EM             185
1780                         Third Party-->EM             174
1647                                       SM             173

In [131]:
pat3 = pd.DataFrame(agg3['Channel'].value_counts()).reset_index()
pat3.columns = ['Conv_path', 'Frequency']
print(pat3.shape)

(1896, 2)

In [132]:
pat3.head(30)

                                  Conv_path  Frequency
0                               Third Party      42929
1                                        EM      25657
2                                   Organic      19686
3                                   Display      16623
4                                   EM-->EM      12473
5                                        DM      11770
6                                       SEM      10689
7                              EM-->EM-->EM       6300
8                 Third Party-->Third Party       3634
9                         Display-->Display       3548
10                        EM-->EM-->EM-->EM       3270
11                                  DM-->DM       2073
12                   EM-->EM-->EM-->EM-->EM       1330
13                                  DM-->EM       1164
14              Display-->Display-->Display        961
15                             EM-->Display        809
16                    Third Party-->Display        788
17                             DM-->EM-->EM        787
18                    Display-->Third Party        787
19                        Organic-->Organic        768
20                                   Social        696
21  Third Party-->Third Party-->Third Party        577
22                        EM-->EM-->Display        546
23              EM-->EM-->EM-->EM-->EM-->EM        528
24                             DM-->Display        526
25                         EM-->Third Party        439
26                                  EM-->DM        423
27                        DM-->EM-->EM-->EM        422
28                        Organic-->Display        387
29    Display-->Display-->Display-->Display        341

In [50]:
# Checking counts

In [134]:
print(EM_data['CURR_AG_IND_ID'].nunique())
print(DM_data['CURR_AG_IND_ID'].nunique())
print(SM_data['CURR_AG_IND_ID'].nunique())
print(Digital_data4['CURR_AG_IND_ID'].nunique())

57376
22425
1285
57051

In [55]:
pd.DataFrame(set(EM_data['CURR_AG_IND_ID']).intersection(DM_data['CURR_AG_IND_ID'])).nunique()

0    7183
dtype: int64

In [56]:
pd.DataFrame(set(EM_data['CURR_AG_IND_ID']).intersection(SM_data['CURR_AG_IND_ID'])).nunique()

0    791
dtype: int64

In [133]:
pd.DataFrame(set(EM_data['CURR_AG_IND_ID']).intersection(Digital_data4['CURR_AG_IND_ID'])).nunique()

0    7289
dtype: int64

In [135]:
pd.DataFrame(set(DM_data['CURR_AG_IND_ID']).intersection(Digital_data4['CURR_AG_IND_ID'])).nunique()

0    2559
dtype: int64